### ISSUE TITLE
When is the first stable release coming? 

### ISSUE THREAD

**Issue by pharshdev** [terrabythia/dart_chromecast#11]

**Comment by terrabythia** [comment]
Haven't had much time to work on this project for a while (starting a new job, other obligations) but I'm planning to put more time in it in the coming months. A stable release date I can't give you, since this is just a project I do on the side when I have the time.

I know the disclaimer says not to use it, but I heard of other developers using it in production without any (or much) problems, so maybe you should take the disclaimer lightly and just try if it works as-is for your project right now.

**Comment by NBTX** [comment]
We're using it in production at ApolloTV on both iOS and Android and it's working perfectly.
If you're having any issues with it, I can take a look for you. It'd probably benefit us too.

**Comment by terrabythia** [comment]
@NBTX wow, that's so cool! Wish I had an Android device to download the app to. 

@pharshdev Closing this issue now. You can try the framework as-is, just like NBTX, and if you're having problems you can open a new issue and I'll be glad to take a look at it. :)

**Comment by snaeji** [comment]
Thanks to @terrabythia for all the great work!

@NBTX could you send me a link to the app?
We are using it in our Android app [here](https://play.google.com/store/apps/details?id=is.ruv.flutterspilari)

**Comment by NBTX** [comment]
@snaeji https://apollotv.xyz/ ;)

**Comment by terrabythia** [comment]
@NBTX Your website says you have both an Android and iOS app. How would I go about installing the app on my iOS device?

**Comment by NBTX** [comment]
@terrabythia We have a TestFlight link. (Website is not updated.)
https://apollotv.xyz/apple/
