### ISSUE TITLE
Is it possible to change playback speed while casting?

### ISSUE THREAD

**Issue by subhash279** [terrabythia/dart_chromecast#23]
Hi,
Thank you so much for this awesome plugin. I was just wondering if it is possible to change playback speed of the casted audio/video? I couldn't find it anywhere in the code. 
Thanks!

**Comment by terrabythia** [comment]
I'm not sure if that's even possible at all with Chromecast. Never saw it as a possibility in any app that supported Chromecast and also never seen anything about it in the Chromecast docs.

My guess is that it isn't possible, sorry!

**Comment by subhash279** [comment]
@terrabythia turns out your plugin already handles it. I just had to add 'playbackRate' as another variable under type, autoPlay, currentTime etc in toChromeCastMap() of CastMedia.

But again great work on the plugin. I am suprised more people aren't using it already!

**Comment by terrabythia** [comment]
Oh, that's great news! But you actually mean the plugin **doesn't** already support it, because you had to add a new property to the Map the toChromeCastMap method returns in the CastMedia class, right?

Would be great if you could share it with everybody by creating a pull request including this new feature! The better we all as a community make this plugin the more people are probably going to use it! ;)

**Comment by subhash279** [comment]
It was just a small change and submmited a PR: #24 
Thanks for the plugin again :)

**Comment by terrabythia** [comment]
Sorry for the delay.. your pull request is merged into the master branch. Thanks for your help!
