### ISSUE TITLE
Adding support for sound null safety

### ISSUE THREAD

**Issue by guyluz11** [terrabythia/dart_chromecast#47]
Moving to `null safety` should be **top priority**.

Without support for `null safety` this package will not get new users as everybody is moving to it.

It is stopping me from using this package and I am sure it is not just me.

**Comment by terrabythia** [comment]
@guyluz11 maybe I'm missing something, but null safety support was added 9 months ago in version 0.2.5 (see the changelog: https://github.com/terrabythia/dart_chromecast/blob/master/CHANGELOG.md).

**Comment by terrabythia** [comment]
I see what you mean now. It's complaining that one of the transitive dependencies doesn't support null safety. Unfortunately this is because the current `protoc_plugin` uses an old version of that library and there is no newer version yet.

<img width="818" alt="Schermafbeelding 2022-01-07 om 16 27 59" src="https://user-images.githubusercontent.com/1402868/148566540-c4f96db0-2f7d-47e8-a54b-7fe9f8c8141d.png">

If you can find a way to fix this anyway feel free to create a PR!

**Comment by guyluz11** [comment]
I have opened an issue for google after opening this issue

https://github.com/google/protobuf.dart/issues/540 and [this](https://github.com/google/protobuf.dart/issues/537) is related too.

As @JishnuM wrote we can use dependency override and it should work.
In another project of mine I am using protoc but generating it using protoc program and not dart package, so this is another option.

And I think protoc_plugin belongs in `dev_dependencies` and not in `dependencies` in case we go with keeping it.

Tell me what option you prefer that I will work on.

**Comment by guyluz11** [comment]
@terrabythia can you try removing  protoc_plugin and test if everything is working correctly?, I think it is not needed at all.

**Comment by terrabythia** [comment]
@guyluz11 hm... interesting. `protoc_plugin` is probably only needed to generate the files in `lib/proto`. We can remove it!
